name: Lighthouse CI
on: [push]

jobs:
 Audit:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Lighthouse CLI
        run: |
          npm install -g @lhci/cli
      - name: Starts Lighthouse CI Autorun = Healthcheck + Collect + Assert + Upload
        run: |
          lhci autorun --upload.serverBaseUrl=${{ secrets.SERVER_BASE_URL }} --upload.token=${{ secrets.BUILD_TOKEN }} || echo "LHCI Assert did not Passed "
